install:
  - npm install
language      : objective-c
xcode_project : ./ios/GithubNoteTaker.xcodeproj
xcode_scheme  : GithubNoteTaker
osx_image     : xcode7
xcode_sdk     : iphonesimulator9.0
xctool_args   : -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
