install:
  - npm install
language      : objective-c
xcode_project : ./ios/GithubNoteTaker.xcodeproj
xcode_scheme  : GithubNoteTaker
osx_image     : xcode6.4
xcode_sdk     : iphonesimulator8.4
xctool_args   : -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
